#define OK                              0
#define ERROR_PATH_EMTPY                1
#define ERROR_COULD_NOT_OPEN_FILE       2
#define ERROR_COULD_NOT_ALLOCATE_BUFFER 3
#define ERROR_COULD_NOT_READ_FILE       4
#define ERROR_UNEXPECTED_EOF            5
#define ERROR_EXPECTED_BUT_GOT          6
#define ERROR_UNKNOWN_SYMBOL            7
#define ERROR_CHAR_LIT_LEN              8
#define ERROR_COULD_NOT_PARSE_STMT      9
#define ERROR_INVALID_TYPE_IDENT        10
