#define STMT_EXPR        1
#define STMT_LET         2
#define STMT_IMPORT      3
#define STMT_FUNC_DECL   4
#define STMT_STRUCT_DECL 5
#define STMT_ENUM_DECL   6
#define STMT_BLOCK       7
#define STMT_IF          8
#define STMT_WHILE       9
#define STMT_DELETE      10
#define STMT_RETURN      11
#define STMT_FOR         12
