#define STMT_EXPR       1
#define STMT_LET        2
#define STMT_IMPORT     3
#define STMT_FUNC_DECL  4
#define STMT_BLOCK      5
#define STMT_IF         6
#define STMT_WHILE      7
#define STMT_NEW        8
#define STMT_DELETE     9
