#define TOKEN_ERR 0

#define TOKEN_INT 1
#define TOKEN_IDENT 2

#define TOKEN_LET 3
#define TOKEN_IF 4
#define TOKEN_ELSE 5
#define TOKEN_IMPORT 6
#define TOKEN_DEF 7

#define TOKEN_SEMI 8
#define TOKEN_COMMA 9
#define TOKEN_COLON 10
#define TOKEN_DOT 11
#define TOKEN_EQ 12

#define TOKEN_PLUS 13
#define TOKEN_MINUS 14
#define TOKEN_STAR 15
#define TOKEN_SLASH 16

#define TOKEN_SMALLER 17
#define TOKEN_SMALLER_EQ 18
#define TOKEN_GREATER 19
#define TOKEN_GREATER_EQ 20

#define TOKEN_LPAREN 21
#define TOKEN_RPAREN 22
#define TOKEN_LBRACE 23
#define TOKEN_RBRACE 24
#define TOKEN_STRING 25

#define TOKEN_EOF 26
