#define TY_UNKNOWN          0
#define TY_PTR              1
#define TY_BOOL             2
#define TY_I32              3
#define TY_CHAR             4
#define TY_VOID             5
#define TY_STRING           6
#define TY_FUNC             7
#define TY_MOD              8
#define TY_STRUCT           9
